### ISSUE TITLE
simulating periodic systems or slab with qiskit and cp2k

### ISSUE THREAD

**Issue by KarimElgammal** [mrossinek/qiskit-nature-cp2k#1]
Hi Max!

as I got to know that pyscf plugin for qiskit doesn't support yet periodic boundary conditions that is needed to simulate a slab (I am double checking in this issue https://github.com/qiskit-community/qiskit-nature-pyscf/issues/64)

thus, I was checking if the cp2k package can do that
thanks in advance

**Comment by mrossinek** [comment]
Yes, via the integration provided by this plugin you can perform a periodic simulation using CP2K and carve out an active space to be simulated with Qiskit. This is what we show in this paper: https://arxiv.org/abs/2404.18737. In its supplementary information section you can find a link to some input files for CP2K as an example for how to set this up.

**Comment by KarimElgammal** [comment]
> Yes, via the integration provided by this plugin you can perform a periodic simulation using CP2K and carve out an active space to be simulated with Qiskit. This is what we show in this paper: https://arxiv.org/abs/2404.18737. In its supplementary information section you can find a link to some input files for CP2K as an example for how to set this up.

much appreciated, very insightful article by the way and great useful contribution by sharing supplementary materials, very rare to find such openness
