### ISSUE TITLE
reproducing calculation workflow in arXiv:2404.18737

### ISSUE THREAD

**Issue by KarimElgammal** [mrossinek/qiskit-nature-cp2k#3]
Hi Max,
## update on 20240821: I think I passed this point now and the socket is working, I was stuck in the classical part as I believe cp2k stable version moved the poisson solver from ERI inside the active space. I tested with simpler system and working.

I am trying to run the package and used the same inputs in the supp. material, but it seems I didn't manage to make it working yet. I start the cp2k first then meanwhile, the active space through the tool.
The calculation doesn't go beyond the memory allocation for Hartree-Fock Exchange as shown in this screenshot:
<img width="593" alt="Screenshot 2024-08-15 at 02 06 38" src="https://github.com/user-attachments/assets/8aeb6757-32c5-4321-b647-bd21bf718c07">

I believe I should have a socket file created, but nothing yet, so I wanted to share my workflow so you can judge

**Here comes some details how I worked on reproducing:**
- I am trying with VQE in 'F0_center > srLDA > as_2_5 > conv_2x2x2 > mu_0.14 > rks_singlet@1Ag'
- I made docker image with cp2k 2024.1, qiskit 0.45 and qiskit-nature 0.7.0 as specified, kindly the below Dockerfile and run.sh I used

### The used `Dockerfile`:
```Dockerfile
FROM cp2k/cp2k:2024.1_openmpi_generic_psmp

RUN apt-get update && apt-get install -y \
    python3-pip \
    git \
    openmpi-bin \
    libopenmpi-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --upgrade pip

RUN git clone -b qiskit_0.45_cp2k_2024.1 https://github.com/KarimElgammal/qiskit-nature-cp2k.git && \
    cd qiskit-nature-cp2k && \
    pip3 install .

RUN pip3 install qiskit-aer mpi4py

WORKDIR /workspace

COPY MgO.inp /workspace/
COPY MgO.xyz /workspace/
COPY client-vqe-ucc.py /workspace/
COPY run_calculation.sh /workspace/

RUN chmod +x /workspace/run_calculation.sh

ENV CP2K_DATA_DIR=/opt/cp2k/data
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

CMD ["tail", "-f", "/dev/null"]
```

### The `run_calculation.sh` is:
```bash
#!/bin/bash
set -e

NUM_MPI_PROCESSES=48
export OMP_NUM_THREADS=2
export OMP_STACKSIZE=1G

rm -f *.log
rm -f embedding_socket

echo "Starting CP2K with MPI..."

mpirun -np ${NUM_MPI_PROCESSES} cp2k -i MgO.inp > cp2k_output.log 2>&1 &
CP2K_PID=$!

echo "CP2K PID: $CP2K_PID"
echo "Waiting for CP2K to initialize..."

socket_created=false
for i in {1..300}; do
    if [ -S embedding_socket ]; then
        echo "Socket file created after $i seconds"
        socket_created=true
        break
    fi
    if [ $((i % 60)) -eq 0 ]; then
        echo "CP2K process status after $i seconds:"
        ps -p $CP2K_PID -o pid,cmd,state,start,etime,time
        echo "Last 20 lines of CP2K output:"
        tail -n 20 cp2k_output.log
    fi
    sleep 1
done

if ! $socket_created; then
    echo "Socket file not created after 300 seconds. CP2K may still be running."
    echo "Last 50 lines of CP2K output:"
    tail -n 50 cp2k_output.log
    echo "Continuing with the Python client..."
fi

echo "Starting the VQE client..."
python3 -u client-vqe-ucc.py --nalpha 1 --nbeta 1 --norbs 5 2>&1 | tee python_output.log

echo "Waiting for CP2K to finish..."
wait $CP2K_PID

echo "Experiment completed"
echo "CP2K output:"
cat cp2k_output.log

echo "Python client output:"
cat python_output.log
```

### The `pip` list:
```bash
Package            Version     Editable project location
------------------ ----------- -------------------------
dill               0.3.8
h5py               3.11.0
mpmath             1.3.0
numpy              1.26.4
pbr                6.0.0
pip                22.0.2
ply                3.11
psutil             6.0.0
python-dateutil    2.9.0.post0
qiskit             0.45.0
qiskit-algorithms  0.3.0
qiskit-nature      0.7.0
qiskit-nature-cp2k 0.0.1       /qiskit-nature-cp2k
qiskit-terra       0.45.0
rustworkx          0.15.1
scipy              1.14.0
setuptools         59.6.0
six                1.16.0
stevedore          5.2.0
symengine          0.9.2
sympy              1.13.2
typing_extensions  4.12.2
wheel              0.37.1
```

much appreciated your support!

**Comment by KarimElgammal** [comment]
I will close the issue then after the update on 20240821: I think I passed this point now and the socket is working, I was stuck in the classical part as I believe cp2k stable version moved the poisson solver from ERI inside the active space. I tested with simpler system and working

**Comment by jonathan-owens** [comment]
@KarimElgammal Do you have an example input file that ended up working? I am new to CP2K and am having issues even figuring out how to get CP2K set up to listen on sockets.

**Comment by KarimElgammal** [comment]
Marc's article has open source data already, for me, I have this working https://archive.materialscloud.org/record/2024.211
